tagOwners:
  tag:sentry:
    - fool

acls:
  - action: accept
    src:
      - user:sudhanva
      - user:samartha
    dst:
      - tag:sentry:25565

  - action: accept
    src:
      - user:fool
    dst:
      - tag:sentry:*

  - action: deny
    src:
      - "*"
    dst:
      - "*"
